fix : check pwd in allure history cache

diff --git a/.github/workflows/e2e-playwright-test.yml b/.github/workflows/e2e-playwright-test.yml
--- a/.github/workflows/e2e-playwright-test.yml
+++ b/.github/workflows/e2e-playwright-test.yml
@@ -177,10 +177,14 @@ jobs:
         ls -R allure-history || echo "(not found or empty)"
 
     - name: Update Allure history cache
+      run: |
+        echo "Caching allure-history directory..."
+        ls -R allure-history || echo "Allure history directory not found"
       uses: actions/cache@v3
       with:
         path: allure-history
         key: ${{ runner.os }}-allure-history-${{ env.SANITIZED_REF }}
+
 
     - name: Upload Allure Report
       if: always()
